---
- name: Elimina repos enterprise
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Agrega repos community
  apt_repository:
    repo: deb "{{ repo }}" buster pve-no-subscription
    state: present

- name: Actualiza la cache de los repos
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalación de pip
  apt:
    name: ['python3-pip', 'python3-dev', 'build-essential']

- name: Actualizacion de pip
  pip:
    name: pip
    state: latest

- name: Instalacion de dependencias ansible
  pip:
    name: ['requests', 'proxmoxer']
